#!/usr/bin/env python3
"""bootstrap-agent.py — One-command Chronicle setup for AI agents.

Usage:
    python bootstrap-agent.py --name "MyAgent" --db ~/.myagent-memory.db
    
Creates:
  - Memory database
  - Initial preferences/context
  - Sample integration code
  - Basic .gitignore for the DB
"""

import argparse
import sys
from pathlib import Path

# Try to import Chronicle
try:
    from chronicle import Chronicle
except ImportError:
    print("❌ Chronicle not installed. Run from the chronicle/ directory or:")
    print("   pip install -e .")
    sys.exit(1)


SAMPLE_AGENT_CODE = '''#!/usr/bin/env python3
"""
{agent_name} — AI agent with Chronicle memory persistence
Generated by Chronicle bootstrap
"""

from chronicle import Chronicle
from datetime import datetime


class {class_name}:
    def __init__(self, db_path="{db_path}"):
        self.memory = Chronicle(db_path)
        self.load_recent_context()
    
    def load_recent_context(self, days=1):
        """Load recent memories on startup."""
        since = f"{days} day ago"
        recent = self.memory.search("", limit=20, since=since)
        
        if recent:
            print(f"📚 Loaded {{len(recent)}} recent memories")
            for mem in recent[:5]:
                print(f"  - {{mem.timestamp}}: {{mem.content[:60]}}...")
        else:
            print("✨ Fresh start — no recent memories")
    
    def remember(self, content, tags=None, source="agent"):
        """Store a memory."""
        tags = tags or []
        self.memory.add(content=content, tags=tags, source=source)
        print(f"💾 Remembered: {{content[:60]}}...")
    
    def recall(self, query, tags=None, limit=5):
        """Search memories."""
        results = self.memory.search(query, tags=tags, limit=limit)
        print(f"🔍 Found {{len(results)}} memories for: {{query}}")
        return results
    
    def learn_preference(self, preference):
        """Store a user preference."""
        self.remember(
            content=preference,
            tags=["preference"],
            source="user-stated"
        )
    
    def get_preferences(self):
        """Get all stored preferences."""
        return self.recall("", tags=["preference"], limit=100)
    
    def log_session_start(self):
        """Mark session start."""
        self.remember(
            content=f"Session started at {{datetime.now().isoformat()}}",
            tags=["meta", "session"],
            source="system"
        )
    
    def log_session_end(self):
        """Mark session end."""
        self.remember(
            content=f"Session ended at {{datetime.now().isoformat()}}",
            tags=["meta", "session"],
            source="system"
        )


def main():
    agent = {class_name}()
    agent.log_session_start()
    
    # Example usage
    print("\\n🌀 {{agent_name}} is ready!")
    print("\\nTry these commands:")
    print("  agent.remember('Built my first tool today', tags=['achievement'])")
    print("  agent.recall('tool')")
    print("  agent.learn_preference('I prefer concise responses')")
    print("  agent.get_preferences()")
    
    return agent


if __name__ == "__main__":
    agent = main()
    
    # Keep agent in scope for interactive use
    print("\\n💡 Agent instance available as 'agent'")
    import code
    code.interact(local={{**globals(), **locals()}})
'''


def bootstrap(agent_name: str, db_path: str, interactive: bool = True):
    """Bootstrap a new AI agent with Chronicle memory."""
    
    print(f"🌀 Bootstrapping {agent_name}...")
    print(f"   Database: {db_path}\n")
    
    # Create database
    db = Path(db_path).expanduser()
    memory = Chronicle(str(db))
    
    # Add initial context
    initial_memories = [
        {
            "content": f"{agent_name} initialized with Chronicle memory system",
            "tags": ["meta", "init"],
            "source": "bootstrap"
        },
        {
            "content": "Use memory.search() to find relevant context before responding",
            "tags": ["best-practice", "reminder"],
            "source": "bootstrap"
        },
        {
            "content": "Tag memories consistently: conversation, preference, tool, error, decision, meta",
            "tags": ["best-practice", "reminder"],
            "source": "bootstrap"
        },
    ]
    
    for mem in initial_memories:
        memory.add(**mem)
    
    print("✅ Database created")
    print(f"✅ Added {len(initial_memories)} initial memories\n")
    
    # Generate sample code
    class_name = "".join(word.capitalize() for word in agent_name.split())
    code_path = db.parent / f"{agent_name.lower().replace(' ', '_')}.py"
    
    sample_code = SAMPLE_AGENT_CODE.format(
        agent_name=agent_name,
        class_name=class_name,
        db_path=str(db)
    )
    
    code_path.write_text(sample_code)
    code_path.chmod(0o755)
    
    print(f"✅ Sample agent code: {code_path}")
    
    # Create .gitignore
    gitignore_path = db.parent / ".gitignore"
    gitignore_content = f"""# Chronicle memory database
{db.name}
*.db
*.db-journal
"""
    
    if not gitignore_path.exists():
        gitignore_path.write_text(gitignore_content)
        print(f"✅ Created .gitignore")
    
    # Success summary
    print("\n" + "="*60)
    print(f"🎉 {agent_name} is ready!")
    print("="*60)
    print(f"\nQuick start:")
    print(f"  python {code_path}")
    print(f"\nOr use the Chronicle API directly:")
    print(f"  from chronicle import Chronicle")
    print(f"  memory = Chronicle('{db}')")
    print(f"  memory.add(content='...', tags=['...'])")
    print(f"  results = memory.search('...')")
    print(f"\nDocumentation:")
    print(f"  cat AI-AGENT-SETUP.md")
    print("\n🌀 Chronicle: Memory continuity for AI agents")


def main():
    parser = argparse.ArgumentParser(
        description="Bootstrap Chronicle memory for an AI agent",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    
    parser.add_argument(
        "--name",
        required=True,
        help="Agent name (e.g., 'MyAgent')"
    )
    
    parser.add_argument(
        "--db",
        required=True,
        help="Path to memory database (e.g., ~/.myagent-memory.db)"
    )
    
    args = parser.parse_args()
    
    bootstrap(
        agent_name=args.name,
        db_path=args.db
    )


if __name__ == "__main__":
    main()
